# Codecov Configuration for Python Project
# Documentation: https://docs.codecov.com/docs/codecov-yaml

# Coverage configuration
coverage:
  precision: 2  # Number of decimal places
  round: down   # Round down or up
  range: "70...100"  # Color range (red to green)

  # Status checks (GitHub)
  status:
    project:
      default:
        target: 80%           # Target coverage (you have 100%!)
        threshold: 2%         # Allow 2% drop
        if_ci_failed: error   # Fail if CI fails
        informational: false  # Block PR if below target

    patch:
      default:
        target: 80%           # Target for new code
        threshold: 2%
        if_ci_failed: error

    changes:
      default:
        if_ci_failed: error

# Comment configuration for Pull Requests
comment:
  layout: "header, diff, flags, files, footer"
  behavior: default  # Update the same comment
  require_changes: false
  require_base: false
  require_head: true
  after_n_builds: 3  # Wait for all 3 Python versions before commenting

# Flags for organizing coverage by Python version
flags:
  python-3.10:
    carryforward: true

  python-3.11:
    carryforward: true

  python-3.12:
    carryforward: true

# Ignore paths (don't measure coverage on these)
ignore:
  - "tests/**/*"           # Don't measure test coverage
  - "**/__pycache__/**/*"  # Python cache
  - "**/venv/**/*"         # Virtual environment
  - "**/htmlcov/**/*"      # Coverage HTML reports
  - "**/.pytest_cache/**/*" # Pytest cache
  - "**/dist/**/*"         # Distribution files
  - "**/build/**/*"        # Build files
  - "**/*.pyc"             # Compiled Python
  - "setup.py"             # Setup script (if you add one)

# GitHub checks configuration
github_checks:
  annotations: true

# Codecov bot configuration (using global org token)
codecov:
  max_report_age: off  # Disable age check to prevent timestamp issues
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

# Optional: Slack notifications
# Uncomment and configure if you want Slack notifications
# slack:
#   url: "secret:SLACK_WEBHOOK_URL"
#   notify: true
#   after_n_builds: 3
#   branches:
#     - master
